### PR TITLE
feat/refactor_external_secrets_operator__external_secret

### PR DESCRIPTION
**Pull request by yairavalosHobOps**
# Title
### Description
Refactoring ExternalSecretsOperator_ExternalSecret template

### Changes
- examples
- templates
- chart

### CODE REVIEW

**Comment by yairavalosHobOps** [comment]
Input command:

./scripts/helm_chart_test.sh charts/common-library charts/common-library/examples/ExternalSecretsOperator_ExternalSecret.yaml

**Comment by yairavalosHobOps** [comment]
Output:

==> Linting charts/common-library

1 chart(s) linted, 0 chart(s) failed


## *Warning: *

example ExternalSecretsOperator_ExternalSecret is empty --> No existe el equivalente en test-values.yaml revisarlo con @admin-hobops

**Comment by inetshell** [comment]
> Output:
> 
> ==> Linting charts/common-library
> 
> 1 chart(s) linted, 0 chart(s) failed
> ## *Warning: *
> 
> example ExternalSecretsOperator_ExternalSecret is empty --> No existe el equivalente en test-values.yaml revisarlo con @admin-hobops

Intenta con este ejemplo:
```
ExternalSecret:
  example-aws-parameterstore:
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-parameterstore
    dataFrom:
    - extract: { key: '/test/example' }
```

**Comment by yairavalosHobOps** [comment]
Se actualizó conforme a la retro
```
Validaciones

Input command:

- ./scripts/helm_chart_test.sh charts/common-library charts/common-library/examples/ExternalSecretsOperator_ExternalSecret.yaml

Output:

==> Linting charts/common-library

1 chart(s) linted, 0 chart(s) failed
---
# Source: common-library/templates/ExternalSecretsOperator_ExternalSecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-aws-parameterstore
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameterstore
  dataFrom:
    - extract:
        key: /test/example


Status:

- En espera de aprobación de @admin-hobops 

```

**Review by inetshell — APPROVED** [review]
LGTM

**Review by inetshell — APPROVED** [review]
LGTM

**Pull request merged**
