### PR TITLE
feat/refactor_external_secrets_operator__cluster_secret_store

### PR DESCRIPTION
**Pull request by yairavalosHobOps**
# Title
### Description
Refactoring ExternalSecretesOperator_ClusterSecretStore Template

### Changes
- example
- templates
- chart

### CODE REVIEW

**Comment by yairavalosHobOps** [comment]
Input command:

./scripts/helm_chart_test.sh charts/common-library charts/common-library/examples/ExternalSecretsOperator_ClusterSecretStore.yaml

**Comment by yairavalosHobOps** [comment]
Output:

==> Linting charts/common-library

1 chart(s) linted, 0 chart(s) failed

## *Warning: *

Example ExternalSecretsOperator_ClusterSecretStore is empty --> No se encontró el equivalente en test-values.yaml revisarlo con @admin-hobops

**Comment by inetshell** [comment]
> Output:
> 
> ==> Linting charts/common-library
> 
> 1 chart(s) linted, 0 chart(s) failed
> ## *Warning: *
> 
> Example ExternalSecretsOperator_ClusterSecretStore is empty --> No se encontró el equivalente en test-values.yaml revisarlo con @admin-hobops

Utiliza este ejemplo:
```
ClusterSecretStore:
  aws-secretsmanager:
    provider:
      aws:
        service: SecretsManager
        region: us-east-1
  aws-parameterstore:
    provider:
      aws:
        service: ParameterStore
        region: us-east-1
  vault-secretstore:
    provider:
      vault:
        auth:
          kubernetes:
            mountPath: kubernetes
            role: external-secrets-operator
            serviceAccountRef:
              name: external-secrets-operator
              namespace: infra
        path: secrets
        server: http://vault.infra.svc.cluster.local:8200
        version: v2
```

**Comment by yairavalosHobOps** [comment]
Update

Input command:
```
- ./scripts/helm_chart_test.sh charts/common-library charts/common-library/examples/ExternalSecretsOperator_ClusterSecretStore.yaml

Output:

==> Linting charts/common-library

1 chart(s) linted, 0 chart(s) failed
---
# Source: common-library/templates/ExternalSecretsOperator_ClusterSecretStore.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameterstore
  namespace: default
spec:
  controller: 
  provider:
    aws:
      region: us-east-1
      service: ParameterStore
---
# Source: common-library/templates/ExternalSecretsOperator_ClusterSecretStore.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  namespace: default
spec:
  controller: 
  provider:
    aws:
      region: us-east-1
      service: SecretsManager
---
# Source: common-library/templates/ExternalSecretsOperator_ClusterSecretStore.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secretstore
  namespace: default
spec:
  controller: 
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets-operator
          serviceAccountRef:
            name: external-secrets-operator
            namespace: infra
      path: secrets
      server: http://vault.infra.svc.cluster.local:8200
      version: v2
```
En espera de aprobación de @admin-hobops

**Review by inetshell — APPROVED** [review]
LGTM

**Pull request merged**
